# -*- coding: utf-8 -*-
"""EDA.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WKYJty-1PXECXo_0K_fMY6LQM9qtA5qx
"""

import pandas as pd

df=pd.read_csv("monthly-beer-production-in-austr.csv")

df.head()

df.head()

(476, 2)

df.count

df.describe

df.columns

import pandas as pd
import matplotlib.pyplot as plt

data = [["1956-01",93.2],
["1956-02",96],
["1956-03",	95.2],
["1956-04",	77.1],
["1956-05",	70.9],
["1956-06",	64.8],
["1956-07",	70.1],
["1956-08",	77.3],
["1956-09",	79.5],
["1956-10",	100.6] ]

# dataframe created with
# the above data array
df = pd.DataFrame(data, columns = ['Month', 'Monthly beer production'] )

df.hist()

# show plot
plt.show()

data = [["1956-01",93.2],
["1956-02",96],
["1956-03",	95.2],
["1956-04",	77.1],
["1956-05",	70.9],
["1956-06",	64.8],
["1956-07",	70.1],
["1956-08",	77.3],
["1956-09",	79.5],
["1956-10",	100.6] ]


df = pd.DataFrame(data, columns = ['Month', 'Monthly beer production'] )

df.plot.bar()

# plot between 2 attributes
plt.bar(df['Month'], df['Monthly beer production'])
plt.xlabel("Month")
plt.ylabel("Monthly beer production")
plt.show()

