# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TW2uIysP8p3ftP7srIfL6qwO19dLV6FV
"""

print("HELLO WORLD")

#Print the length of your name::
name=input("Enter your name: ")
length=len(name)
print(length)

#Input the names and ages of two people and print their total:
name=input("Enter your name: ")
age=int(input("Enter your age: "))
name=input("Enter your name: ")
age1=int(input("Enter your age: "))
Sum=int(age+age1)
print("The sum of the two ages is", Sum)

#Input three numbers and calcualte their average(mean)
a=int(input("Enter a number= "))
b=int(input("Enter a number= "))
c=int(input("Enter a number= "))
Averagemean=int(a+b+c/3)
print("The average mean is: ", Averagemean)

#Enter the dimensions of a rectangular box and calculate its volume:
l=12
b=9
h=12
volume=int(l*b*h)
print("The volume of rectangular box is",volume)

#Python program to find the HCF of two numbers:
def compute_hcf(x,y):
  #smaller=0
    if x > y:
        smaller = x
    else:
         smaller = y
    for i in range(1, smaller+1):
      if((x % i == 0) and (y % i == 0)):
        hcf=i
    return hcf
a=12
b=14
print("The hcf of",a,"and",b,"is", compute_hcf(a,b))

#Draw the pattern::
for i in range(1,6):
  for j in range(1, i+1):
    print("*", end= "")

#To find factorial of a number::
def factorial(n):
    return 1 if (n==1 or n==0) else n * factorial(n-1)

number = 6
print("The factorial of", number, "is", factorial(number))

#Display all duplicate from the list::
l=[10,20,30,10,40,20,40,50,60,30]
dict={i:None for i in l}
l2=list(dict.keys());
print(l2)

#To find the sum of natural numbers::
number=int(input("Enter a number: "))
if number < 0:
  print("positive number")
else:
  sum = 0

  while(number>0):
    sum += number
    number -= 1
  print("The sum is", sum)

